// packages/client/src/shared/ui/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react';
import { useTheme } from '../theme/theme.ts';
import { ToolbarButton } from './ToolbarButton.tsx';

export function ThemeToggle({ compact = false }: { compact?: boolean }) {
  const current = useTheme((state) => state.current);
  const toggle = useTheme((state) => state.toggle);
  const nextTheme = current === 'dark' ? 'light' : 'dark';
  return (
    <ToolbarButton
      compact={compact}
      onClick={toggle}
      label={`Switch to ${nextTheme} theme`}
      title={`Switch to ${nextTheme} theme`}
    >
      {current === 'dark' ? (
        <Sun size={18} strokeWidth={1.8} aria-hidden="true" />
      ) : (
        <Moon size={18} strokeWidth={1.8} aria-hidden="true" />
      )}
    </ToolbarButton>
  );
}

// src/lib/theme/ThemeToggle.svelte
<script lang="ts">
import Moon from '@lucide/svelte/icons/moon';
import Sun from '@lucide/svelte/icons/sun';
import ToolbarButton from '$lib/ui/ToolbarButton.svelte';
import { themeState } from './theme.svelte';

let { compact = false }: { compact?: boolean } = $props();
const nextTheme = $derived(themeState.current === 'dark' ? 'light' : 'dark');
</script>

<ToolbarButton
  {compact}
  onclick={() => themeState.toggle()}
  label={`Switch to ${nextTheme} theme`}
  title={`Switch to ${nextTheme} theme`}
>
  {#if themeState.current === 'dark'}
    <Sun size={18} strokeWidth={1.8} aria-hidden="true" />
  {:else}
    <Moon size={18} strokeWidth={1.8} aria-hidden="true" />
  {/if}
</ToolbarButton>
