// packages/client/src/features/status/StatusPluginBar.tsx
import * as Popover from '@radix-ui/react-popover';
import type { StatusPluginMenuEntry, StatusPluginSnapshot } from '@vampire/lib/shared/contracts/status-plugin.ts';
import { AlertTriangle, ExternalLink, Settings2, X } from 'lucide-react';
import { useState } from 'react';
import './status-plugin-bar.css';

function timestamp(at: number) {
  return new Intl.DateTimeFormat(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(at);
}
function Progress({ value, label }: { value: number; label: string }) {
  const percent = Math.max(0, Math.min(100, value));
  return (
    <span
      className="status-progress"
      role="progressbar"
      aria-label={label}
      aria-valuemin={0}
      aria-valuemax={100}
      aria-valuenow={percent}
    >
      <span style={{ width: `${percent}%` }} />
    </span>
  );
}
function MenuEntry({ entry }: { entry: StatusPluginMenuEntry }) {
  if (entry.type === 'separator') return <hr />;
  if (entry.type === 'heading')
    return (
      <div className="status-menu-heading">
        <strong>{entry.text}</strong>
        {entry.badge ? <span className="status-menu-badge">{entry.badge}</span> : null}
      </div>
    );
  const content = (
    <>
      <div className="status-menu-row">
        <strong>
          {entry.checked ? '✓ ' : ''}
          {entry.text}
        </strong>
        {entry.badge ? <span className="status-menu-badge">{entry.badge}</span> : null}
        {entry.value ? <output>{entry.value}</output> : null}
        {entry.href ? <ExternalLink size={13} aria-hidden="true" /> : null}
      </div>
      <div className="status-menu-description">
        {entry.detail ? <small>{entry.detail}</small> : null}
        {entry.time ? (
          <small>
            {entry.time.label ?? 'At'} {timestamp(entry.time.at)}
          </small>
        ) : null}
      </div>
      {entry.progress !== undefined ? <Progress value={entry.progress} label={entry.text} /> : null}
    </>
  );
  return entry.href ? (
    <a className="status-menu-item" data-tone={entry.tone} href={entry.href} target="_blank" rel="noreferrer">
      {content}
    </a>
  ) : (
    <div className="status-menu-item" data-tone={entry.tone}>
      {content}
    </div>
  );
}

export function StatusPluginBar({ onManage, plugins }: { onManage: () => void; plugins: StatusPluginSnapshot[] }) {
  const [openId, setOpenId] = useState<string>();
  const openPlugin = plugins.find((plugin) => plugin.id === openId);
  return (
    <Popover.Root open={Boolean(openPlugin)} onOpenChange={(open) => !open && setOpenId(undefined)}>
      <section className="status-plugin-bar" aria-label="Server status plugins">
        <div>
          {plugins.map((plugin) => {
            const button = (
              <button
                type="button"
                aria-expanded={openId === plugin.id}
                aria-label={`${plugin.name}${plugin.text ? `: ${plugin.text}` : ''}`}
                title={plugin.tooltip}
                onPointerDown={(event) => {
                  if (event.button === 0) setOpenId((current) => (current === plugin.id ? undefined : plugin.id));
                }}
                onClick={(event) => {
                  if (event.detail === 0) setOpenId((current) => (current === plugin.id ? undefined : plugin.id));
                }}
              >
                <span>{plugin.name}</span>
                <output>{plugin.state === 'loading' ? '…' : (plugin.text ?? '—')}</output>
                {plugin.state === 'error' || plugin.state === 'stale' ? (
                  <AlertTriangle size={12} aria-hidden="true" />
                ) : null}
              </button>
            );
            return (
              <div key={plugin.id} className="status-plugin">
                {openId === plugin.id ? <Popover.Anchor asChild>{button}</Popover.Anchor> : button}
              </div>
            );
          })}
          <button
            type="button"
            className="status-manage"
            aria-label="Manage status widgets"
            title="Manage status widgets"
            onClick={onManage}
          >
            <Settings2 size={14} strokeWidth={1.9} aria-hidden="true" />
          </button>
        </div>
      </section>
      {openPlugin ? (
        <Popover.Portal>
          <Popover.Content
            className="status-plugin-popover"
            aria-label={`${openPlugin.name} details`}
            data-tone={openPlugin.tone}
            sideOffset={8}
            collisionPadding={8}
            align="start"
            sticky="always"
            onOpenAutoFocus={(event) => event.preventDefault()}
            onPointerDownOutside={(event) => {
              const target = event.detail.originalEvent.target;
              if (target instanceof Element && target.closest('.status-plugin > button')) event.preventDefault();
            }}
          >
            <header>
              <div className="status-plugin-summary">
                <strong>{openPlugin.name}</strong>
                <output>{openPlugin.state === 'loading' ? 'Loading…' : (openPlugin.text ?? '—')}</output>
              </div>
              <Popover.Close className="status-plugin-close" aria-label={`Close ${openPlugin.name} details`}>
                <X size={16} aria-hidden="true" />
              </Popover.Close>
              {openPlugin.progress !== undefined ? (
                <Progress value={openPlugin.progress} label={openPlugin.name} />
              ) : null}
            </header>
            {openPlugin.menu?.length ? (
              <div className="status-plugin-menu">
                {openPlugin.menu.map((entry, index) => (
                  <MenuEntry key={`${entry.type}-${index}`} entry={entry} />
                ))}
              </div>
            ) : null}
            {openPlugin.error ? (
              <p className="status-plugin-error" role="status">
                <AlertTriangle size={14} aria-hidden="true" />
                <span>{openPlugin.error}</span>
              </p>
            ) : null}
            {openPlugin.updatedAt ? (
              <time dateTime={new Date(openPlugin.updatedAt).toISOString()}>
                Updated {timestamp(openPlugin.updatedAt)}
              </time>
            ) : null}
          </Popover.Content>
        </Popover.Portal>
      ) : null}
    </Popover.Root>
  );
}

// src/lib/status/StatusPluginBar.svelte
<script lang="ts">
	import { Popover } from 'bits-ui';
	import Check from '@lucide/svelte/icons/check';
	import ExternalLink from '@lucide/svelte/icons/external-link';
	import AlertTriangle from '@lucide/svelte/icons/triangle-alert';
	import Settings2 from '@lucide/svelte/icons/settings-2';
	import type { StatusPluginMenuEntry, StatusPluginSnapshot } from './status-plugin.ts';
	import StatusPluginSettings from './StatusPluginSettings.svelte';

	type StatusPluginItem = Extract<StatusPluginMenuEntry, { type: 'item' }>;

	let { plugins }: { plugins: StatusPluginSnapshot[] } = $props();
	let settingsOpen = $state(false);
	let closedByOutsidePointer = false;

	function timestampLabel(timestamp: number): string {
		return new Intl.DateTimeFormat(undefined, {
			month: 'short',
			day: 'numeric',
			hour: 'numeric',
			minute: '2-digit',
			second: '2-digit'
		}).format(new Date(timestamp));
	}

	function pluginLabel(plugin: StatusPluginSnapshot): string {
		if (plugin.state === 'loading') return `${plugin.name} is loading`;
		const value = plugin.text ? `: ${plugin.text}` : '';
		const error = plugin.error ? `. ${plugin.error}` : '';
		return `${plugin.name}${value}${error}`;
	}

	function handleInteractOutside() {
		closedByOutsidePointer = true;
	}

	function handleCloseAutoFocus(event: Event) {
		if (!closedByOutsidePointer) return;
		closedByOutsidePointer = false;
		event.preventDefault();
	}

</script>

{#snippet menuItemContent(entry: StatusPluginItem)}
	<div class="status-plugin-menu-item__content">
		<div class="status-plugin-menu-item__title">
			{#if entry.checked}<Check size={13} strokeWidth={2.2} aria-hidden="true" />{/if}
			<span>{entry.text}</span>
			{#if entry.badge}<em>{entry.badge}</em>{/if}
		</div>
		{#if entry.detail}<small>{entry.detail}</small>{/if}
		{#if entry.time}
			<small>{entry.time.label ?? 'At'} {timestampLabel(entry.time.at)}</small>
		{/if}
	</div>
	{#if entry.value}<output>{entry.value}</output>{/if}
	{#if entry.href}<ExternalLink class="status-plugin-menu-item__external" size={12} strokeWidth={1.8} aria-hidden="true" />{/if}
	{#if entry.progress !== undefined}
		<div class="status-plugin-menu-progress" role="progressbar" aria-label={`${entry.text} progress`} aria-valuenow={entry.progress} aria-valuemin="0" aria-valuemax="100">
			<span style={`width: ${entry.progress}%`}></span>
		</div>
	{/if}
{/snippet}

<section class="status-plugin-bar" aria-label="Server status plugins">
	<div class="status-plugin-scroll">
		<div class="status-plugin-list">
			{#each plugins as plugin (plugin.id)}
				<Popover.Root>
					<Popover.Trigger
						type="button"
						class={`status-plugin${plugin.state === 'error' || plugin.state === 'stale' ? ' status-plugin--problem' : ''}`}
						data-tone={plugin.tone ?? 'neutral'}
						aria-label={pluginLabel(plugin)}
						title={plugin.tooltip}
					>
						<span>{plugin.name}</span>
						<output>{plugin.state === 'loading' ? '…' : plugin.text ?? '—'}</output>
						{#if plugin.state === 'error' || plugin.state === 'stale'}
							<AlertTriangle size={12} strokeWidth={2} aria-hidden="true" />
						{/if}
					</Popover.Trigger>
					<Popover.Portal>
						<Popover.Content
							class="status-plugin-popover"
							side="bottom"
							align="start"
							sideOffset={6}
							trapFocus={false}
							onInteractOutside={handleInteractOutside}
							onCloseAutoFocus={handleCloseAutoFocus}
						>
							<div class="status-plugin-popover__header">
								<strong>{plugin.name}</strong>
								<output>{plugin.state === 'loading' ? 'Loading…' : plugin.text ?? '—'}</output>
							</div>
							{#if plugin.progress !== undefined}
								<div class="status-plugin-progress" role="progressbar" aria-label={`${plugin.name} usage`} aria-valuenow={plugin.progress} aria-valuemin="0" aria-valuemax="100">
									<span style={`width: ${plugin.progress}%`}></span>
								</div>
							{/if}
							{#if plugin.menu?.length}
								<div class="status-plugin-menu" role="list">
									{#each plugin.menu as entry}
										{#if entry.type === 'separator'}
											<div class="status-plugin-menu-separator" role="separator"></div>
										{:else if entry.type === 'heading'}
											<div class="status-plugin-menu-heading">
												<strong>{entry.text}</strong>
												{#if entry.badge}<span>{entry.badge}</span>{/if}
											</div>
										{:else}
											<div
												class="status-plugin-menu-item"
												data-tone={entry.tone ?? 'neutral'}
												style={`--status-menu-indent: ${(entry.indent ?? 0) * 0.8}rem`}
												role="listitem"
											>
												{#if entry.href}
													<a href={entry.href} target="_blank" rel="noreferrer">{@render menuItemContent(entry)}</a>
												{:else}
													<div>{@render menuItemContent(entry)}</div>
												{/if}
											</div>
										{/if}
									{/each}
								</div>
							{/if}
							{#if plugin.error}<p class="status-plugin-error" role="status">{plugin.error}</p>{/if}
							<div class="status-plugin-times">
								{#if plugin.updatedAt}<span>Updated {timestampLabel(plugin.updatedAt)}</span>{/if}
							</div>
						</Popover.Content>
					</Popover.Portal>
				</Popover.Root>
			{/each}
		</div>
	</div>
	<button
		type="button"
		class="status-plugin-settings"
		onclick={() => settingsOpen = true}
		aria-label="Manage status plugins"
		aria-expanded={settingsOpen}
		title="Manage status plugins"
	>
		<Settings2 size={15} strokeWidth={1.8} aria-hidden="true" />
	</button>
</section>

{#if settingsOpen}
	<StatusPluginSettings close={() => settingsOpen = false} />
{/if}

<style>
	.status-plugin-bar { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: stretch; min-width: 0; min-height: 2.15rem; border-top: 1px solid var(--color-border-subtle); border-bottom: 1px solid var(--color-border-subtle); background: var(--color-surface-sunken); color: var(--color-text-secondary); }
	.status-plugin-scroll { min-width: 0; overflow-x: auto; overscroll-behavior-x: contain; scrollbar-width: none; }
	.status-plugin-scroll::-webkit-scrollbar { display: none; }
	.status-plugin-list { display: flex; align-items: stretch; width: max-content; min-width: 100%; padding-left: max(0.45rem, env(safe-area-inset-left)); }
	:global(.status-plugin) { display: inline-flex; flex: 0 0 auto; align-items: center; gap: 0.34rem; min-height: 2.15rem; padding: 0 0.58rem; border: 0; border-right: 1px solid var(--color-border-subtle); background: transparent; color: var(--color-text-secondary); font: inherit; font-size: var(--text-caption); font-variant-numeric: tabular-nums; white-space: nowrap; cursor: pointer; }
	:global(.status-plugin:hover), :global(.status-plugin:focus-visible) { background: var(--color-surface-hover); color: var(--color-text); }
	:global(.status-plugin > span) { color: var(--color-text-tertiary); font-weight: var(--weight-medium); }
	:global(.status-plugin output) { color: var(--color-text); font: inherit; }
	:global(.status-plugin[data-tone='success'] output) { color: var(--color-success-text); }
	:global(.status-plugin[data-tone='warning'] output), :global(.status-plugin--problem) { color: var(--color-warning-accent); }
	:global(.status-plugin[data-tone='danger'] output), :global(.status-plugin--problem > svg) { color: var(--color-danger-text); }
	.status-plugin-settings { display: grid; place-items: center; width: 2.4rem; min-height: 2.15rem; padding: 0; border: 0; border-left: 1px solid var(--color-border); background: var(--color-panel); color: var(--color-text-tertiary); cursor: pointer; }
	.status-plugin-settings:hover, .status-plugin-settings:focus-visible { background: var(--color-surface-hover); color: var(--color-text); }
	:global(.status-plugin-popover) { z-index: 70; display: grid; gap: 0.55rem; width: max-content; min-width: 13rem; max-width: min(24rem, calc(100vw - 1rem)); padding: 0.7rem; border: 1px solid var(--color-border-strong); border-radius: var(--radius-md); outline: none; background: var(--color-surface-overlay); box-shadow: var(--shadow-popover); color: var(--color-text-secondary); font-size: var(--text-caption); }
	:global(.status-plugin-popover__header) { display: flex; align-items: baseline; justify-content: space-between; gap: 1rem; }
	:global(.status-plugin-popover__header strong) { color: var(--color-text); font-weight: var(--weight-medium); }
	:global(.status-plugin-popover__header output) { color: var(--color-text); font: inherit; font-weight: var(--weight-strong); font-variant-numeric: tabular-nums; }
	:global(.status-plugin-progress) { height: 0.3rem; overflow: hidden; border-radius: var(--radius-pill); background: var(--color-surface-sunken); }
	:global(.status-plugin-progress span) { display: block; height: 100%; border-radius: inherit; background: var(--color-accent); }
	:global(.status-plugin-menu) { display: grid; overflow: hidden; border: 1px solid var(--color-border-subtle); border-radius: var(--radius-sm); background: var(--color-surface-sunken); }
	:global(.status-plugin-menu-heading) { display: flex; align-items: center; justify-content: space-between; gap: 0.75rem; padding: 0.48rem 0.55rem; border-bottom: 1px solid var(--color-border-subtle); background: var(--color-surface-raised); color: var(--color-text-secondary); }
	:global(.status-plugin-menu-heading strong) { min-width: 0; overflow-wrap: anywhere; font-weight: var(--weight-strong); }
	:global(.status-plugin-menu-heading span) { flex: 0 0 auto; padding: 0.08rem 0.34rem; border: 1px solid var(--color-border-subtle); border-radius: var(--radius-pill); color: var(--color-text-tertiary); font-size: var(--text-nano); font-weight: var(--weight-medium); }
	:global(.status-plugin-menu-separator) { height: 0.42rem; border-top: 1px solid var(--color-border-subtle); border-bottom: 1px solid var(--color-border-subtle); background: var(--color-surface-overlay); }
	:global(.status-plugin-menu-item > a), :global(.status-plugin-menu-item > div) { display: grid; grid-template-columns: minmax(0, 1fr) auto auto; gap: 0.12rem 0.65rem; align-items: baseline; padding: 0.48rem 0.55rem 0.48rem calc(0.55rem + var(--status-menu-indent)); color: inherit; text-decoration: none; }
	:global(.status-plugin-menu-item + .status-plugin-menu-item) { border-top: 1px solid var(--color-border-subtle); }
	:global(.status-plugin-menu-item > a:hover), :global(.status-plugin-menu-item > a:focus-visible) { outline: none; background: var(--color-surface-hover); }
	:global(.status-plugin-menu-item__content) { display: grid; min-width: 0; gap: 0.08rem; }
	:global(.status-plugin-menu-item__title) { display: flex; min-width: 0; align-items: center; gap: 0.32rem; color: var(--color-text-secondary); }
	:global(.status-plugin-menu-item__title > span) { overflow-wrap: anywhere; }
	:global(.status-plugin-menu-item__title em) { padding: 0.08rem 0.32rem; border-radius: var(--radius-pill); background: var(--color-surface-raised); color: var(--color-text-tertiary); font-size: var(--text-nano); font-style: normal; }
	:global(.status-plugin-menu-item__content small) { color: var(--color-text-tertiary); font: inherit; font-size: var(--text-nano); }
	:global(.status-plugin-menu-item output) { color: var(--color-text); font: inherit; font-weight: var(--weight-strong); font-variant-numeric: tabular-nums; white-space: nowrap; }
	:global(.status-plugin-menu-item__external) { align-self: center; color: var(--color-text-tertiary); }
	:global(.status-plugin-menu-item[data-tone='success'] .status-plugin-menu-item__title), :global(.status-plugin-menu-item[data-tone='success'] output) { color: var(--color-success-text); }
	:global(.status-plugin-menu-item[data-tone='warning'] .status-plugin-menu-item__title), :global(.status-plugin-menu-item[data-tone='warning'] output) { color: var(--color-warning-accent); }
	:global(.status-plugin-menu-item[data-tone='danger'] .status-plugin-menu-item__title), :global(.status-plugin-menu-item[data-tone='danger'] output) { color: var(--color-danger-text); }
	:global(.status-plugin-menu-progress) { grid-column: 1 / -1; height: 0.22rem; margin-top: 0.2rem; overflow: hidden; border-radius: var(--radius-pill); background: var(--color-surface-raised); }
	:global(.status-plugin-menu-progress span) { display: block; height: 100%; border-radius: inherit; background: var(--color-accent); }
	:global(.status-plugin-error) { margin: 0; padding: 0.42rem 0.5rem; border-radius: var(--radius-sm); background: var(--color-danger-surface); color: var(--color-danger-text); line-height: var(--leading-ui); }
	:global(.status-plugin-times) { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 0.35rem 1rem; color: var(--color-text-tertiary); font-size: var(--text-nano); }

	@media (max-width: 32rem) {
		.status-plugin-list { padding-left: max(0.2rem, env(safe-area-inset-left)); }
		:global(.status-plugin) { padding-inline: 0.48rem; }
		.status-plugin-settings { width: max(2.65rem, calc(2.4rem + env(safe-area-inset-right))); padding-right: env(safe-area-inset-right); }
	}
</style>
