// src/lib/terminal/TerminalViewport.svelte
<script lang="ts">
	import CircleAlert from '@lucide/svelte/icons/circle-alert';
	import MonitorSmartphone from '@lucide/svelte/icons/monitor-smartphone';
	import RefreshCw from '@lucide/svelte/icons/refresh-cw';
	import { onMount, untrack, type Snippet } from 'svelte';
	import TerminalInputDock from './TerminalInputDock.svelte';
	import ShellOpening from './ShellOpening.svelte';
	import { TerminalImagePasteState } from './image-paste-state.svelte';
	import {
		TerminalRuntime,
		type TerminalOpeningStage,
		type TerminalRuntimeState
	} from './terminal-runtime.ts';
	import { terminalFontFamily, terminalTheme, THEME_CHANGE_EVENT } from '$lib/theme/theme.svelte';
	import { isDesktopViewport } from '$lib/ui/layout';
	import {
		parseWorkspaceEntryDrag,
		WORKSPACE_ENTRY_DRAG_TYPE,
		workspaceEntryDragText,
		type TerminalPathInsertionRequest,
		type WorkspaceEntryDragData
	} from '$lib/workspace-entry-drag.ts';
	import '@xterm/xterm/css/xterm.css';

	let {
		sessionId,
		terminalId,
		onInputActivity = () => undefined,
		onOutputActivity = () => undefined,
		onRepositoryStatus = () => undefined,
		pathInsertionRequest,
		onExternalFileDrop = async () => [],
		fontSize = $bindable(14),
		minimumFontSize = 10,
		maximumFontSize = 22,
		children
	}: {
		sessionId: string;
		terminalId?: string;
		onInputActivity?: (sessionId: string, timestamp: number) => void;
		onOutputActivity?: (sessionId: string, active: boolean, timestamp?: number) => void;
		onRepositoryStatus?: (changeCount: number, worktreeCount: number) => void;
		pathInsertionRequest?: TerminalPathInsertionRequest;
		onExternalFileDrop?: (dataTransfer: DataTransfer) => Promise<WorkspaceEntryDragData[]>;
		fontSize?: number;
		minimumFontSize?: number;
		maximumFontSize?: number;
		children?: Snippet;
	} = $props();

	let terminalElement: HTMLDivElement;
	let runtime = $state<TerminalRuntime>();
	let terminalError = $state('');
	let connected = $state(false);
	let controlSizeMismatch = $state(false);
	let controlsTerminal = $state<boolean>();
	let terminalReconnecting = $state(false);
	let terminalOutputPaused = $state(false);
	let screenReady = $state(false);
	let openingVisible = $state(false);
	let openingStage = $state<TerminalOpeningStage>('opening');
	let directInputFocused = $state(false);
	let terminalDropKind = $state<'' | 'path' | 'files'>('');
	let addingDroppedFiles = $state(false);
	let droppedFileError = $state('');
	let handledPathInsertionToken = 0;
	const imagePaste = new TerminalImagePasteState(
		untrack(() => sessionId),
		untrack(() => terminalId),
		() => connected
	);

	function applyRuntimeState(state: Readonly<TerminalRuntimeState>) {
		connected = state.connected;
		controlSizeMismatch = state.controlSizeMismatch;
		controlsTerminal = state.controlsTerminal;
		directInputFocused = state.directInputFocused;
		openingStage = state.openingStage;
		openingVisible = state.openingVisible;
		screenReady = state.screenReady;
		terminalError = state.error;
		terminalOutputPaused = state.outputPaused;
		terminalReconnecting = state.reconnecting;
	}

	function changeTerminalFontSize(delta: number) {
		fontSize = Math.min(maximumFontSize, Math.max(minimumFontSize, fontSize + delta));
	}

	function handleTerminalPointerDown(event: PointerEvent) {
		if (event.pointerType === 'touch') return;
		runtime?.focus();
		if (isDesktopViewport()) directInputFocused = true;
	}

	function dataTransferTypes(event: DragEvent): string[] {
		return Array.from(event.dataTransfer?.types ?? []);
	}

	function handleTerminalDragOver(event: DragEvent) {
		if (!connected || addingDroppedFiles || !event.dataTransfer) return;
		const types = dataTransferTypes(event);
		const kind = types.includes(WORKSPACE_ENTRY_DRAG_TYPE)
			? 'path'
			: types.includes('Files') ? 'files' : '';
		if (!kind) return;
		event.preventDefault();
		event.dataTransfer.dropEffect = 'copy';
		terminalDropKind = kind;
	}

	function handleTerminalDragLeave() {
		terminalDropKind = '';
	}

	async function handleTerminalDrop(event: DragEvent) {
		terminalDropKind = '';
		if (!connected || addingDroppedFiles || !event.dataTransfer) return;
		const raw = event.dataTransfer?.getData(WORKSPACE_ENTRY_DRAG_TYPE);
		const entry = raw ? parseWorkspaceEntryDrag(raw) : undefined;
		if (entry) {
			event.preventDefault();
			runtime?.focus();
			runtime?.send(workspaceEntryDragText(entry));
			return;
		}
		if (!dataTransferTypes(event).includes('Files')) return;
		event.preventDefault();
		addingDroppedFiles = true;
		droppedFileError = '';
		try {
			const entries = await onExternalFileDrop(event.dataTransfer);
			if (entries.length === 0) return;
			runtime?.focus();
			runtime?.send(entries.map(workspaceEntryDragText).join(' '));
		} catch (error) {
			droppedFileError = error instanceof Error ? error.message : 'The dropped files could not be added.';
		} finally {
			addingDroppedFiles = false;
		}
	}

	$effect(() => {
		const size = fontSize;
		untrack(() => runtime?.setFontSize(size));
	});

	$effect(() => {
		const request = pathInsertionRequest;
		if (!request || request.token === handledPathInsertionToken || !connected || !runtime) return;
		handledPathInsertionToken = request.token;
		runtime.focus();
		runtime.send(request.entries.map(workspaceEntryDragText).join(' '));
	});

	onMount(() => {
		const handleClipboardPaste = (event: ClipboardEvent) => {
			void imagePaste.handleClipboardPaste(event);
		};
		window.addEventListener('paste', handleClipboardPaste, true);
		const terminalRuntime = new TerminalRuntime({
			element: terminalElement,
			sessionId,
			terminalId,
			fontSize,
			minimumFontSize,
			maximumFontSize,
			themeChangeEvent: THEME_CHANGE_EVENT,
			getFontFamily: terminalFontFamily,
			getTheme: terminalTheme,
			onFontSizeChange: (size) => fontSize = size,
			onInputActivity,
			onOutputActivity,
			onRepositoryStatus,
			onStateChange: applyRuntimeState
		});
		runtime = terminalRuntime;
		terminalRuntime.start();

		return () => {
			window.removeEventListener('paste', handleClipboardPaste, true);
			terminalRuntime.dispose();
			imagePaste.dispose();
			if (runtime === terminalRuntime) runtime = undefined;
		};
	});
</script>

<div class="terminal-body">
	<div class="terminal-frame">
		<div
			class="terminal"
			class:path-drop-target={Boolean(terminalDropKind)}
			class:direct-input={directInputFocused}
			class:screen-ready={screenReady}
			bind:this={terminalElement}
			onpointerdown={handleTerminalPointerDown}
			ondragenter={handleTerminalDragOver}
			ondragover={handleTerminalDragOver}
			ondragleave={handleTerminalDragLeave}
			ondrop={(event) => void handleTerminalDrop(event)}
			role="application"
			aria-label="Interactive shell terminal"
		></div>
		{#if terminalDropKind}
			<div class="terminal-drop-prompt" aria-hidden="true">
				{terminalDropKind === 'files' ? 'Copy to workspace and insert path' : 'Insert path into terminal'}
			</div>
		{/if}
		{#if connected && screenReady && controlsTerminal === false}
			<div class="terminal-control-handoff" role="status" aria-live="polite">
				<span class="terminal-status-icon control" aria-hidden="true">
					<MonitorSmartphone size={16} strokeWidth={1.8} />
				</span>
				<span class="terminal-control-label">
					{controlSizeMismatch ? 'Sized for another device' : 'Layout controlled by another device'}
				</span>
				<button type="button" onclick={() => runtime?.claimControl()}>Use this device</button>
			</div>
		{/if}
		{#if !terminalError}
			<ShellOpening
				ready={screenReady}
				visible={openingVisible && !terminalReconnecting && !terminalError}
				stage={openingStage}
			/>
		{/if}
		{#if terminalError}
			<div class="terminal-status-card terminal-error" role="alert">
				<span class="terminal-status-icon error" aria-hidden="true">
					<CircleAlert size={17} strokeWidth={1.9} />
				</span>
				<span class="terminal-status-message">{terminalError}</span>
				<button type="button" onclick={terminalOutputPaused ? () => runtime?.reconnect() : () => location.reload()}>
					{terminalOutputPaused ? 'Resume output' : 'Reconnect'}
				</button>
			</div>
		{:else if terminalReconnecting}
			<div class="terminal-status-card terminal-connection-status" role="status" aria-live="polite">
				<span class="terminal-status-icon reconnecting" aria-hidden="true">
					<RefreshCw size={16} strokeWidth={1.9} />
				</span>
				<span class="terminal-status-message">Reconnecting to terminal…</span>
				<button type="button" onclick={() => runtime?.reconnect()}>Retry now</button>
			</div>
		{/if}
	</div>
	{#if imagePaste.message}
		<div class="image-paste-notice" class:uploading={imagePaste.kind === 'uploading'} class:error={imagePaste.kind === 'error'} role={imagePaste.kind === 'error' ? 'alert' : 'status'}>
			{imagePaste.message}
		</div>
	{/if}
	{#if addingDroppedFiles || droppedFileError}
		<div class="terminal-file-drop-notice" class:error={Boolean(droppedFileError)} role={droppedFileError ? 'alert' : 'status'}>
			{droppedFileError || 'Adding dropped files…'}
		</div>
	{/if}

	<TerminalInputDock
		{connected}
		send={(data) => runtime?.send(data)}
		submit={(data) => runtime?.submit(data) ?? false}
		scrollToTop={() => runtime?.scrollToTop()}
		scrollToBottom={() => runtime?.scrollToBottom()}
		onComposerFocus={() => runtime?.markComposerFocused()}
		onImageSelected={(image) => void imagePaste.paste(image)}
		{fontSize}
		{minimumFontSize}
		{maximumFontSize}
		decreaseFontSize={() => changeTerminalFontSize(-1)}
		increaseFontSize={() => changeTerminalFontSize(1)}
	/>
	{#if children}{@render children()}{/if}
</div>

<style>
	.terminal-body { position: relative; display: grid; grid-template-rows: minmax(0, 1fr) auto auto auto auto; min-width: 0; min-height: 0; overflow: hidden; }
	.terminal-frame { position: relative; min-width: 0; min-height: 0; overflow: hidden; }
	.terminal { width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; padding: 0.35rem; touch-action: none; }
	.terminal.path-drop-target { box-shadow: inset 0 0 0 2px var(--color-accent); }
	.terminal.direct-input { box-shadow: inset 0 0 0 1px var(--color-visual-accent-glow); }
	.terminal :global(.xterm) { height: 100%; padding: 0.25rem; opacity: 1; touch-action: none; }
	.terminal :global(.xterm-viewport) { overflow-y: scroll; overscroll-behavior: contain; background: var(--color-terminal-background); -webkit-overflow-scrolling: touch; touch-action: none; }
	.terminal :global(.composition-view) { background: var(--color-terminal-background); color: var(--color-terminal-foreground); }
	.terminal :global(.xterm-scrollable-element) { height: 100%; touch-action: none; }
	.terminal-drop-prompt { position: absolute; z-index: 3; left: 50%; bottom: 1rem; padding: 0.45rem 0.68rem; transform: translateX(-50%); border: 1px solid var(--color-accent); border-radius: var(--radius-pill); background: var(--color-panel); box-shadow: var(--shadow-popover); color: var(--color-text); font-size: var(--text-label); pointer-events: none; white-space: nowrap; }
	.terminal-control-handoff { position: absolute; z-index: 4; top: 0.75rem; right: 0.75rem; display: flex; align-items: center; gap: 0.5rem; max-width: calc(100% - 1.5rem); padding: 0.38rem; border: 1px solid var(--color-border); border-radius: 0.78rem; background: var(--color-surface-overlay); box-shadow: var(--shadow-popover); color: var(--color-text-secondary); font-size: var(--text-label); line-height: var(--leading-ui); white-space: nowrap; }
	.terminal-status-icon { display: grid; flex: 0 0 2rem; place-items: center; width: 2rem; height: 2rem; border-radius: 0.58rem; }
	.terminal-status-icon.control { background: var(--color-accent-soft); color: var(--color-accent-soft-text); }
	.terminal-control-label { padding: 0 0.18rem 0 0.05rem; }
	.terminal-control-handoff button, .terminal-status-card button { flex: 0 0 auto; min-height: 2.25rem; padding: 0 0.72rem; border: 1px solid var(--color-border); border-radius: 0.55rem; background: var(--color-surface-selected); color: var(--color-text); font: inherit; font-weight: var(--weight-medium); cursor: pointer; touch-action: manipulation; }
	.terminal-control-handoff button:hover, .terminal-status-card button:hover { border-color: var(--color-border-strong); background: var(--color-control-hover); }
	.terminal-control-handoff button:focus-visible, .terminal-status-card button:focus-visible { outline: none; box-shadow: var(--shadow-accent-focus); }
	.terminal-status-card { position: absolute; z-index: 5; right: 0.75rem; bottom: 0.75rem; display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 0.55rem; width: max-content; max-width: min(30rem, calc(100% - 1.5rem)); padding: 0.45rem; border: 1px solid var(--color-border-strong); border-radius: 0.78rem; background: var(--color-surface-overlay); box-shadow: var(--shadow-popover); color: var(--color-text-secondary); font-size: var(--text-label); line-height: var(--leading-ui); }
	.terminal-status-message { min-width: 0; padding: 0 0.2rem 0 0.05rem; text-align: left; }
	.terminal-status-icon.error { background: var(--color-danger-surface); color: var(--color-danger-text); }
	.terminal-error { border-color: var(--color-danger-border); }
	.terminal-error button { border-color: var(--color-danger-border); color: var(--color-danger-text-strong); }
	.terminal-status-icon.reconnecting { background: var(--color-warning-surface); color: var(--color-warning-accent); }
	.terminal-connection-status .terminal-status-icon :global(svg) { animation: terminal-status-spin 0.9s linear infinite; }
	.image-paste-notice { display: flex; align-items: center; justify-content: center; gap: 0.75rem; margin: 0; padding: 0.45rem 0.75rem; font-size: var(--text-label); line-height: var(--leading-ui); text-align: center; }
	.image-paste-notice { border-top: 1px solid var(--color-border); background: var(--color-success-surface); color: var(--color-success-text); }
	.image-paste-notice.uploading { background: var(--color-warning-surface); color: var(--color-command); }
	.image-paste-notice.error { background: var(--color-danger-surface-strong); color: var(--color-danger-text); }
	.terminal-file-drop-notice { padding: 0.45rem 0.75rem; border-top: 1px solid var(--color-border); background: var(--color-warning-surface); color: var(--color-command); font-size: var(--text-label); line-height: var(--leading-ui); text-align: center; }
	.terminal-file-drop-notice.error { background: var(--color-danger-surface-strong); color: var(--color-danger-text); }

	@media (max-width: 32rem) {
		.terminal-control-handoff { top: 0.5rem; right: 0.5rem; width: auto; max-width: calc(100% - 1rem); }
		.terminal-control-label { flex: 0 1 auto; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
		.terminal-control-handoff button, .terminal-status-card button { min-height: 2.75rem; }
		.terminal-status-card { right: 0.5rem; bottom: 0.5rem; width: calc(100% - 1rem); max-width: none; }
	}

	@keyframes terminal-status-spin { to { transform: rotate(360deg); } }

	@media (prefers-reduced-motion: reduce) {
		.terminal :global(.xterm) { transition: none; }
		.terminal-connection-status .terminal-status-icon :global(svg) { animation: none; }
	}
</style>

// packages/client/src/features/terminal/TerminalViewport.tsx
import { ArrowLeftRight, CircleAlert, Ellipsis, ImagePlus, MonitorSmartphone, RefreshCw, Send } from 'lucide-react';
import { observer } from 'mobx-react-lite';
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  acquireTerminalRuntime,
  releaseTerminalRuntime,
  type TerminalRuntime,
  type TerminalRuntimeState,
} from '@vampire/lib/features/terminal/ui/terminal-runtime.ts';
import { loadComposerDraft, saveComposerDraft } from '@vampire/lib/features/terminal/model/composer-draft-storage.ts';
import {
  parseWorkspaceEntryDragEntries,
  type WorkspaceEntryDragData,
  WORKSPACE_ENTRY_DRAG_TYPE,
  workspaceEntryDragText,
} from '@vampire/lib/shared/lib/workspace-entry-drag.ts';
import {
  isInputSurfaceToggleShortcut,
  type TerminalControlKey,
} from '@vampire/lib/features/terminal/model/terminal-control.ts';
import { loadTerminalFontSize } from '@vampire/lib/features/terminal/model/terminal-display-preference.ts';
import {
  loadLastFocusedInputSurface,
  saveLastFocusedInputSurface,
  type TerminalInputSurface,
} from '@vampire/lib/features/terminal/model/input-surface-preference.ts';
import type { TerminalInputSettings } from '@vampire/lib/shared/contracts/terminal-input.ts';
import type { WorkspaceComposerPrompt } from '@vampire/lib/shared/contracts/workspace-composer-history.ts';
import { renderComposerTemplate } from '@vampire/lib/shared/lib/composer-template.ts';
import { requestJson } from '~/shared/api/request.ts';
import { THEME_CHANGE_EVENT, terminalFontFamily, terminalTheme } from '~/shared/theme/theme.ts';
import { Button, Textarea, ToolbarButton } from '~/shared/ui/index.ts';
import { ComposerHistoryPopover } from './ComposerHistoryPopover.tsx';
import { SubmissionRecovery } from './model/submission-recovery.ts';
import '@xterm/xterm/css/xterm.css';
import './terminal-viewport.css';

const EMPTY_COMPOSER_CONTROLS: Partial<Record<string, TerminalControlKey>> = {
  Escape: 'escape',
  Backspace: 'backspace',
  ArrowUp: 'arrow-up',
  ArrowDown: 'arrow-down',
  ArrowLeft: 'arrow-left',
  ArrowRight: 'arrow-right',
};
const INITIAL_STATE: TerminalRuntimeState = {
  connected: false,
  controlSizeMismatch: false,
  controlsTerminal: undefined,
  error: '',
  inputReady: false,
  openingStage: 'opening',
  openingVisible: false,
  reconnecting: false,
  screenReady: false,
};
const DEFAULT_INPUT: TerminalInputSettings = { mode: 'terminal', slashHandoff: true };

type Props = {
  composerHistoryEnabled: boolean;
  composerTemplate?: string;
  composerTemplateContext: { workspace: { cwd: string; name: string } };
  onInputActivity: (workspaceId: string, timestamp: number) => void;
  onLoadComposerPrompts: (workspaceId: string, refresh?: boolean) => Promise<WorkspaceComposerPrompt[]>;
  onOutputActivity: (workspaceId: string, active: boolean, timestamp?: number) => void;
  onRecordComposerPrompt: (workspaceId: string, prompt: string) => Promise<void>;
  onRepositoryStatus: (changeCount: number, worktreeCount: number, branch?: string) => void;
  onWorkspaceObserved: (workspaceId: string) => void;
  onUploadFiles?: (dataTransfer: DataTransfer) => Promise<string[]>;
  pathInsertion?: { entry: WorkspaceEntryDragData; token: number };
  terminalId?: string;
  workspaceId: string;
};

export const TerminalViewport = observer(function TerminalViewport(props: Props) {
  const {
    composerHistoryEnabled,
    composerTemplate,
    composerTemplateContext,
    onInputActivity,
    onLoadComposerPrompts,
    onOutputActivity,
    onRecordComposerPrompt,
    onRepositoryStatus,
    onWorkspaceObserved,
    onUploadFiles,
    pathInsertion,
    terminalId,
    workspaceId,
  } = props;
  const terminalElement = useRef<HTMLDivElement>(null);
  const composerElement = useRef<HTMLTextAreaElement>(null);
  const imageInput = useRef<HTMLInputElement>(null);
  const runtime = useRef<TerminalRuntime | null>(null);
  const activityCallbacks = useRef({ onInputActivity, onOutputActivity, onRepositoryStatus, onWorkspaceObserved });
  activityCallbacks.current = { onInputActivity, onOutputActivity, onRepositoryStatus, onWorkspaceObserved };
  const [runtimeState, setRuntimeState] = useState<TerminalRuntimeState>(INITIAL_STATE);
  const [recovery] = useState(() => new SubmissionRecovery(workspaceId, terminalId));
  const [draft, setDraft] = useState(() => loadComposerDraft(workspaceId, terminalId).value);
  const [templateWarning, setTemplateWarning] = useState('');
  const [imageError, setImageError] = useState('');
  const [uploadingImage, setUploadingImage] = useState(false);
  const [messageActionsOpen, setMessageActionsOpen] = useState(false);
  const [terminalDropKind, setTerminalDropKind] = useState<'' | 'files' | 'path'>('');
  const [inputSettings, setInputSettings] = useState(DEFAULT_INPUT);
  const [inputSurface, setInputSurface] = useState<TerminalInputSurface>(
    () => loadLastFocusedInputSurface(workspaceId, terminalId).value ?? 'compose'
  );
  const loadPrompts = useCallback(() => onLoadComposerPrompts(workspaceId), [onLoadComposerPrompts, workspaceId]);

  useEffect(() => {
    let active = true;
    void requestJson<TerminalInputSettings>('/api/terminal-input/settings', { cache: 'no-store' })
      .then((value) => {
        if (!active) return;
        setInputSettings(value);
      })
      .catch(() => undefined);
    return () => {
      active = false;
    };
  }, []);
  useEffect(() => {
    const closeDesktopActions = () => {
      if (!window.matchMedia('(max-width: 32rem)').matches) setMessageActionsOpen(false);
    };
    window.addEventListener('resize', closeDesktopActions);
    return () => window.removeEventListener('resize', closeDesktopActions);
  }, []);
  useEffect(() => {
    const element = terminalElement.current;
    if (!element) return;
    const terminalRuntime = acquireTerminalRuntime({
      element,
      workspaceId,
      terminalId,
      fontSize: loadTerminalFontSize(14),
      minimumFontSize: 10,
      maximumFontSize: 22,
      themeChangeEvent: THEME_CHANGE_EVENT,
      getFontFamily: terminalFontFamily,
      getTheme: terminalTheme,
      shouldAutoFocus: () => false,
      onFontSizeChange: () => undefined,
      onComposeShortcut: () => {
        setInputSurface('compose');
        saveLastFocusedInputSurface(workspaceId, terminalId, 'compose');
        composerElement.current?.focus({ preventScroll: true });
      },
      onInputActivity: (id, timestamp) => activityCallbacks.current.onInputActivity(id, timestamp),
      onTerminalInput: () => {
        setInputSurface('terminal');
        saveLastFocusedInputSurface(workspaceId, terminalId, 'terminal');
      },
      onOutputActivity: (id, active, timestamp) => activityCallbacks.current.onOutputActivity(id, active, timestamp),
      onRepositoryStatus: (changeCount, worktreeCount, branch) =>
        activityCallbacks.current.onRepositoryStatus(changeCount, worktreeCount, branch),
      onStateChange: (state) => setRuntimeState({ ...state }),
      onTerminalTap: () => {
        setInputSurface('terminal');
        saveLastFocusedInputSurface(workspaceId, terminalId, 'terminal');
        terminalRuntime.focus();
      },
      onSubmissionResult: (result) => recovery.applyResult(result),
      onSubmissionUncertain: (requestId) => recovery.markUncertain(requestId),
    });
    runtime.current = terminalRuntime;
    terminalRuntime.start();
    return () => {
      runtime.current = null;
      releaseTerminalRuntime(terminalRuntime);
    };
  }, [recovery, terminalId, workspaceId]);
  useEffect(() => {
    if (!pathInsertion || !runtimeState.inputReady) return;
    if (runtime.current?.send(workspaceEntryDragText(pathInsertion.entry))) {
      chooseInputSurface('terminal');
      runtime.current.focus();
    }
  }, [pathInsertion?.token, runtimeState.inputReady]);

  useEffect(() => {
    if (!runtimeState.screenReady) return;
    activityCallbacks.current.onWorkspaceObserved(workspaceId);
    if (document.querySelector('[data-terminal-autofocus="preserve"]')) return;
    if (inputSurface === 'compose') composerElement.current?.focus({ preventScroll: true });
    else runtime.current?.focus();
  }, [inputSurface, runtimeState.screenReady]);

  const chooseInputSurface = (surface: TerminalInputSurface) => {
    setInputSurface(surface);
    saveLastFocusedInputSurface(workspaceId, terminalId, surface);
  };
  const toggleInput = () => {
    const surface = inputSurface === 'compose' ? 'terminal' : 'compose';
    chooseInputSurface(surface);
    if (surface === 'compose') composerElement.current?.focus({ preventScroll: true });
    else runtime.current?.focus();
  };
  const submit = () => {
    if (!draft.trim()) return;
    const prompt = draft;
    const rendered = renderComposerTemplate(composerTemplate, prompt, composerTemplateContext);
    const sent = recovery.submit(
      rendered.text,
      prompt,
      (data, requestId) => runtime.current?.submit(data, requestId) ?? false
    );
    if (!sent) return;
    setTemplateWarning(
      rendered.error
        ? `The Compose template could not be applied, so the original message was sent. ${rendered.error}`
        : ''
    );
    setDraft('');
    saveComposerDraft(workspaceId, terminalId, '');
    void onRecordComposerPrompt(workspaceId, prompt);
  };
  const sendControl = (control: TerminalControlKey) => runtime.current?.sendControl(control);
  const insertPrompt = (text: string) => {
    const element = composerElement.current;
    const start = element?.selectionStart ?? draft.length;
    const end = element?.selectionEnd ?? start;
    const next = `${draft.slice(0, start)}${text}${draft.slice(end)}`;
    setDraft(next);
    saveComposerDraft(workspaceId, terminalId, next);
    window.setTimeout(() => {
      element?.focus();
      element?.setSelectionRange(start + text.length, start + text.length);
    }, 0);
  };
  const uploadImage = async (image: File) => {
    setUploadingImage(true);
    setImageError('');
    const form = new FormData();
    form.set('image', image);
    const query = terminalId ? `?terminal=${encodeURIComponent(terminalId)}` : '';
    try {
      await requestJson(
        `/api/workspaces/${encodeURIComponent(workspaceId)}/image${query}`,
        { method: 'POST', body: form },
        'Unable to send the image to the shell.'
      );
    } catch (cause) {
      setImageError(cause instanceof Error ? cause.message : 'Unable to send the image to the shell.');
    } finally {
      setUploadingImage(false);
    }
  };
  const handleTerminalDrop = async (event: React.DragEvent<HTMLDivElement>) => {
    setTerminalDropKind('');
    const raw = event.dataTransfer.getData(WORKSPACE_ENTRY_DRAG_TYPE);
    const dragged = raw ? parseWorkspaceEntryDragEntries(raw) : undefined;
    if (dragged?.length) {
      event.preventDefault();
      if (runtime.current?.send(dragged.map(workspaceEntryDragText).join(' '))) runtime.current.focus();
      return;
    }
    if (!event.dataTransfer.types.includes('Files')) return;
    event.preventDefault();
    try {
      if (!onUploadFiles) return;
      const entries = (await onUploadFiles(event.dataTransfer)).map((path) => ({ path, kind: 'file' as const }));
      if (entries.length && runtime.current?.send(entries.map(workspaceEntryDragText).join(' ')))
        runtime.current.focus();
    } catch (cause) {
      setImageError(cause instanceof Error ? cause.message : 'The dropped files could not be added.');
    }
  };
  const handleComposerKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.nativeEvent.isComposing || event.keyCode === 229) return;
    if (isInputSurfaceToggleShortcut(event.nativeEvent)) {
      event.preventDefault();
      toggleInput();
      return;
    }
    if (event.ctrlKey && event.altKey && event.key.toLocaleLowerCase() === 'h' && composerHistoryEnabled) {
      event.preventDefault();
      document.querySelector<HTMLButtonElement>('[aria-label="Open Composer history"]')?.click();
      return;
    }
    if (event.ctrlKey && !event.altKey && event.key === '/') {
      event.preventDefault();
      insertPrompt('/');
      return;
    }
    if (event.key === 'Enter' && event.repeat) {
      event.preventDefault();
      return;
    }
    if (draft.length === 0 && !event.shiftKey && !event.ctrlKey && !event.metaKey && !event.altKey) {
      const control = EMPTY_COMPOSER_CONTROLS[event.key];
      if (control) {
        event.preventDefault();
        sendControl(control);
        return;
      }
      if (event.key === '/' && inputSettings.slashHandoff) {
        event.preventDefault();
        runtime.current?.send('/');
        runtime.current?.focus();
        chooseInputSurface('terminal');
        return;
      }
    }
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      if (draft.length === 0) sendControl('enter');
      else submit();
    }
  };

  return (
    <div className="terminal-body">
      <div className="terminal-frame">
        <div
          ref={terminalElement}
          className={`terminal${runtimeState.screenReady ? ' screen-ready' : ''}`}
          role="application"
          aria-label="Interactive shell terminal"
          onDragEnter={(event) => {
            const kind = event.dataTransfer.types.includes(WORKSPACE_ENTRY_DRAG_TYPE)
              ? 'path'
              : event.dataTransfer.types.includes('Files')
                ? 'files'
                : '';
            if (kind) {
              event.preventDefault();
              setTerminalDropKind(kind);
            }
          }}
          onDragOver={(event) => {
            const kind = event.dataTransfer.types.includes(WORKSPACE_ENTRY_DRAG_TYPE)
              ? 'path'
              : event.dataTransfer.types.includes('Files')
                ? 'files'
                : '';
            if (kind) {
              event.preventDefault();
              setTerminalDropKind(kind);
            }
          }}
          onDragLeave={() => setTerminalDropKind('')}
          onDrop={(event) => void handleTerminalDrop(event)}
          onClick={() => {
            chooseInputSurface('terminal');
            runtime.current?.focus();
          }}
        />
        {terminalDropKind ? (
          <div className="terminal-drop-prompt" aria-hidden="true">
            {terminalDropKind === 'files' ? 'Copy to workspace and insert path' : 'Insert path into terminal'}
          </div>
        ) : null}
        {runtimeState.connected && runtimeState.screenReady && runtimeState.controlsTerminal === false ? (
          <div className="terminal-control-handoff" role="status">
            <MonitorSmartphone size={16} aria-hidden="true" />
            <span>
              {runtimeState.controlSizeMismatch ? 'Sized for another device' : 'Layout controlled by another device'}
            </span>
            <Button size="sm" onClick={() => runtime.current?.claimControl()}>
              Use this device
            </Button>
          </div>
        ) : null}
        {runtimeState.error ? (
          <div className="terminal-status-card terminal-error" role="alert">
            <CircleAlert size={17} aria-hidden="true" />
            <span>{runtimeState.error}</span>
            <Button size="sm" variant="danger-outline" onClick={() => location.reload()}>
              Reconnect
            </Button>
          </div>
        ) : runtimeState.reconnecting ? (
          <div className="terminal-status-card terminal-connection-status" role="status">
            <RefreshCw size={16} aria-hidden="true" />
            <span>Reconnecting to terminal…</span>
            <Button size="sm" onClick={() => runtime.current?.reconnect()}>
              Retry now
            </Button>
          </div>
        ) : runtimeState.openingVisible ? (
          <div className="terminal-opening" role="status">
            {runtimeState.openingStage === 'restoring'
              ? 'Restoring terminal…'
              : runtimeState.openingStage === 'attaching'
                ? 'Attaching to terminal…'
                : 'Opening terminal…'}
          </div>
        ) : null}
      </div>
      <div className="terminal-input-region input-dock">
        <div className="touch-toolbar" role="group" aria-label="Terminal controls">
          {(
            [
              ['escape', 'Esc'],
              ['interrupt', 'Ctrl+C'],
              ['tab', 'Tab'],
              ['backspace', 'Backspace'],
              ['enter', 'Enter'],
              ['arrow-up', '↑'],
              ['arrow-down', '↓'],
              ['arrow-left', '←'],
              ['arrow-right', '→'],
            ] as const
          ).map(([control, label]) => (
            <button
              key={control}
              type="button"
              disabled={!runtimeState.inputReady}
              onPointerDown={(event) => event.preventDefault()}
              onClick={() => sendControl(control)}
            >
              {label}
            </button>
          ))}
          {(
            [
              ['Scroll to terminal top', 'Top', () => runtime.current?.scrollToTop()],
              ['Scroll terminal up one page', 'PgUp', () => runtime.current?.scrollPageUp()],
              ['Scroll terminal down one page', 'PgDn', () => runtime.current?.scrollPageDown()],
              ['Scroll to terminal bottom', 'Bottom', () => runtime.current?.scrollToBottom()],
            ] as const
          ).map(([label, text, action]) => (
            <button
              key={label}
              type="button"
              className="wide-key"
              aria-label={label}
              onPointerDown={(event) => event.preventDefault()}
              onClick={action}
            >
              {text}
            </button>
          ))}
        </div>
        {recovery.entries.length ? (
          <div className="submission-recovery" role="region" aria-label="Compose delivery status">
            {recovery.entries.map((entry) => (
              <div key={entry.requestId}>
                <span>{entry.status === 'pending' ? 'Sending message…' : entry.message}</span>
                {entry.status !== 'pending' ? <span aria-label="Draft excerpt">{entry.draft}</span> : null}
                {entry.status !== 'pending' ? (
                  <Button
                    size="sm"
                    aria-label="Restore draft"
                    onClick={() => {
                      setDraft(entry.draft);
                      saveComposerDraft(workspaceId, terminalId, entry.draft);
                      recovery.dismiss(entry.requestId);
                    }}
                  >
                    Restore draft
                  </Button>
                ) : null}
              </div>
            ))}
          </div>
        ) : null}
        {recovery.error ? (
          <p className="composer-notice" role="alert">
            {recovery.error}
          </p>
        ) : null}
        {templateWarning ? (
          <p className="composer-notice" role="status">
            {templateWarning}
          </p>
        ) : null}
        {imageError ? (
          <p className="composer-notice" role="alert">
            {imageError}
          </p>
        ) : null}
        <div className="composer-slot">
          <div className={`terminal-composer composer ${inputSurface}-mode`} role="group" aria-label="Terminal input">
            <button
              className="composer-mode"
              type="button"
              aria-label="Switch between Compose and Terminal"
              title="Switch input"
              onClick={toggleInput}
            >
              <ArrowLeftRight size={18} />
              <span>Switch input</span>
              <kbd>{/Mac|iPhone|iPad|iPod/.test(navigator.userAgent) ? '⌘ /' : 'Ctrl + `'}</kbd>
            </button>
            <Textarea
              ref={composerElement}
              className="composer-editor"
              size="sm"
              rows={1}
              value={draft}
              onInput={(event) => {
                const value = event.currentTarget.value;
                setDraft(value);
                saveComposerDraft(workspaceId, terminalId, value);
              }}
              onKeyDown={handleComposerKeyDown}
              onPointerDown={() => setMessageActionsOpen(false)}
              onPaste={(event) => {
                const image = [...event.clipboardData.files].find((file) => file.type.startsWith('image/'));
                if (image) {
                  event.preventDefault();
                  void uploadImage(image);
                }
              }}
              onFocus={() => chooseInputSurface('compose')}
              onBlur={() => saveComposerDraft(workspaceId, terminalId, draft)}
              placeholder="Compose a message…"
              autoCapitalize="off"
              autoComplete="off"
              spellCheck={false}
              aria-label="Send text to the shell"
            />
            <span className="composer-line-count" hidden={draft.split('\n').length <= 1}>
              + {Math.max(0, draft.split('\n').length - 1)} lines
            </span>
            <div className="composer-secondary-actions">
              {composerHistoryEnabled ? (
                <div>
                  <ComposerHistoryPopover load={loadPrompts} onSelect={insertPrompt} />
                </div>
              ) : null}
              <input
                ref={imageInput}
                type="file"
                hidden
                accept="image/avif,image/gif,image/jpeg,image/png,image/webp"
                onChange={(event) => {
                  const image = event.currentTarget.files?.[0];
                  if (image) void uploadImage(image);
                  event.currentTarget.value = '';
                }}
              />
              <ToolbarButton
                className="image-button"
                label="Send an image to the shell"
                onClick={() => imageInput.current?.click()}
                disabled={!runtimeState.inputReady || uploadingImage}
              >
                <ImagePlus size={18} />
              </ToolbarButton>
            </div>
            <div className="composer-actions">
              <ToolbarButton
                className="composer-actions-trigger"
                label="More message actions"
                active={messageActionsOpen}
                aria-expanded={messageActionsOpen}
                onClick={() => setMessageActionsOpen((open) => !open)}
              >
                <Ellipsis size={18} />
              </ToolbarButton>
              {messageActionsOpen ? (
                <div className="composer-action-list" data-vampire-overlay>
                  {composerHistoryEnabled ? (
                    <button
                      type="button"
                      onClick={() => {
                        setMessageActionsOpen(false);
                        window.setTimeout(
                          () =>
                            document
                              .querySelector<HTMLButtonElement>(
                                '.composer-secondary-actions [aria-label="Open Composer history"]'
                              )
                              ?.click(),
                          0
                        );
                      }}
                    >
                      Open Composer history
                    </button>
                  ) : null}
                  <button
                    type="button"
                    disabled={!runtimeState.inputReady || uploadingImage}
                    onClick={() => {
                      setMessageActionsOpen(false);
                      imageInput.current?.click();
                    }}
                  >
                    Send an image to the shell
                  </button>
                </div>
              ) : null}
            </div>
            <Button
              className="send-button"
              variant="primary"
              aria-label="Send to shell"
              title="Send text and press Enter"
              disabled={!runtimeState.inputReady || !draft.trim()}
              onPointerDown={(event) => event.preventDefault()}
              onClick={submit}
            >
              <Send size={17} />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
});
